package be.heh.projettrica.infra.addaptater.secondary.orm;

import lombok.Data;

import javax.persistence.*;
import java.util.Date;

@Entity
@Data
@Table(name = "tournois") // Specifies the table name in the database that this entity maps to
public class TournoisJpaEntity {
    //constructeur vide
    public TournoisJpaEntity(){

    }

    public TournoisJpaEntity(String name,String jeux,int nbPart,int visible,long numerot){
        this.numerot = Long.parseLong("0");
        this.name=name;
        this.jeux=jeux;
        this.nbPart=nbPart;
        this.visible=visible;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Indicates that the primary key is generated by the database
    @Column(name = "numerot") // Specifies the column name in the table
    private Long numerot;

    @Column(name = "nametournois") // Specifies the column name in the table
    private String name;

    @Column(name = "jeux") // Specifies the column name in the table
    private String jeux;

    @Column(name = "nbpart") // Specifies the column name in the table
    private int nbPart;

    @Column(name = "visible") // Specifies the column name in the table
    private int visible;


}
